version: '3'
services:
  web-server:
    image: 'rizulhanif/geolocation-client:v1'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${VUE_PORT:-8080}:80'
    restart: unless-stopped
    platform: linux/amd64
    working_dir: /usr/share/nginx/html
    container_name: geolocation-client
